name: e_varootra
description: Application mobile de gestion de ventes à crédit - E-VAROOTRA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.7

  # Base de données locale
  drift: ^2.18.0
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # Typographie
  google_fonts: ^6.2.1

  # Graphiques
  fl_chart: ^0.68.0

  # PDF & impression
  pdf: ^3.11.1
  printing: ^5.13.1

  # Utilitaires
  intl: ^0.19.0
  uuid: ^4.4.2
  crypto: ^3.0.3
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.3
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts: []